-- AlterTable
ALTER TABLE "Chat" ADD COLUMN     "title" TEXT NOT NULL DEFAULT '',
ALTER COLUMN "lastMessageText" SET DEFAULT '',
ALTER COLUMN "lastMessageAt" DROP NOT NULL,
ALTER COLUMN "lastMessageAt" SET DEFAULT CURRENT_TIMESTAMP;
